<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>edc</string>
	</array>
	<key>name</key>
	<string>Edje</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(group|part|description|text|program|script)\b</string>
			<key>name</key>
			<string>punctuation.section.group.tex</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(parts|programs)\b</string>
			<key>name</key>
			<string>keyword.other.new</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(COMP|STATE_SET|LINEAR|ACTION_STOP|SINUSOIDAL|ACCELERATE|DECELERATE|TEXT|SHADOW|BOTTOM|RECT|SWALLOW|PROXY|SPACER)\b</string>
			<key>name</key>
			<string>constant.character</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.class</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.variable</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.variable</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.variable</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(([a-zA-Z0-9_]+)(\.))*([a-zA-Z0-9_]+)(:)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(")(.*)(")</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\d+</string>
			<key>name</key>
			<string>constant.numeric</string>
		</dict>
		<dict>
			<key>match</key>
			<string>//.+\n</string>
			<key>name</key>
			<string>comment</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.preprocessor.macro.c</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta.preprocessor.macro.c</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([a-zA-Z_]+\().+(\))</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.edc</string>
	<key>uuid</key>
	<string>90d51037-3a7f-49fd-a331-94126cfa0561</string>
</dict>
</plist>
